# SPDX-FileCopyrightText: Copyright 2025 Siemens
#
# SPDX-License-Identifier: Apache-2.0

# Install target configuration:
option('openssl_modules_dir', type: 'string',
       value: '/lib/x86_64-linux-gnu/ossl-modules',
       description: 'OpenSSL provider directory')

# Default configuration:
option('gta_state_directory', type: 'string', value: '.',
        description: 'Serialization directory')

# Crypto algorithm configuration:
option('ec_on', type: 'boolean', value: true,  
        description: 'Enable Elliptic Curve support')
option('dilithium_on', type: 'boolean', value: false, 
        description: 'Enabel Dilithium (PQC) support')

# Log configurations:
option('log_level', type: 'integer', value: 0,
        description: 'Log level (TRACE 0, DEBUG 1, INFO 2, WARN 3, ERROR 4)')
option('log_b64_on', type: 'boolean', value: true,  
        description: 'Enable to show base64 decoded data in the log')
option('log_byte_array_on', type: 'boolean', value: false, 
        description: 'Enable to show byte array data in the log')
option('log_for_cycle_on', type: 'boolean', value: false, 
        description: 'Enable to show state of the for cycle in the log')

# Global configuration:
option('build_type', type : 'combo', choices : ['debug', 'release' ], value : 'debug', 
        description : 'Select build type with associated tool configuration')


